import type { Metadata } from "next";

import { cn } from "@/lib/utils";

import Nav from "@/components/Nav";
import { Toaster } from "@/components/ui/toaster";

import { Inter as FontSans } from "next/font/google";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

import "./globals.css";

export const metadata: Metadata = {
  title: "Ticket App",
  description: "Generated by Andres Bedoya",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
